### PR TITLE
Oracle APEX HOL 01

### PR DESCRIPTION
**Pull request by RoopeshThokala**
# Add here your WMS ID 11147, 11150

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [Done] All filenames are lower case (including folders, images, files, etc.)
- [Done] Filenames are descriptive
- [Done] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [Done] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [Done] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Make sure all filenames are lower case
2. Can you create a folder named “files” under the lab folder "4-creating-db-objects-quicksql" and put the projects.csv under the “files” folder
3. Both tenancy/manifest.json files should use this link/file as the “Need Help?” Lab: “https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md” 
Thanks!

**Comment by RoopeshThokala** [comment]
Hi Arabella,

I fixed the issues as per your suggestions. Please review the PR.

Thanks & Regards,
Roopesh Thokala

From: Arabella Yao ***@***.***>
Date: Wednesday, 23 November 2022 at 12:24 AM
To: oracle-livelabs/apex ***@***.***>
Cc: Roopesh Thokala ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/apex] Oracle APEX HOL 01 (PR #37)

@arabellayao requested changes on this pull request.

Hi! Please fix the following issues of your PR:

  1.  Make sure all filenames are lower case
  2.  Can you create a folder named “files” under the lab folder "4-creating-db-objects-quicksql" and put the projects.csv under the “files” folder
  3.  Both tenancy/manifest.json files should use this link/file as the “Need Help?” Lab: “https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md”<https://urldefense.com/v3/__https:/oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md**B__;4oCd!!ACWV5N9M2RV99hQ!Ljr550dgzzGuGw0xkrdO8uEWtzjpSQwC5L8B1gcRbccX9Jkt7I5pjpyKVZ8yY88vahBe7qnwrH26RVjBT3A6_1YrOeXY1g$>
Thanks!

**Comment by RoopeshThokala** [comment]
I fixed the issues as per your suggestions. Please review the PR.

**Review by arabellayao — DISMISSED** [review]
Hi! Please rename this Markdown file to lower case: apex-professional-hol1/2-install-run-sample-application/2-Hands-on-Lab-01.md. Everything else looks good. Thanks!

**Comment by madhusudhanrao-ppm** [comment]
file names should be all lowercase

image

**Comment by RoopeshThokala** [comment]
Hi Arabella & Madhu. I updated the file names as per your suggestions.

**Comment by RoopeshThokala** [comment]
Hi Madhu,

I changed the file names to lowercase. Please review the PR and Approve it if everything else is fine.

Thanks & Regards,
Roopesh Thokala.

From: Madhusudhan Rao ***@***.***>
Date: Wednesday, 23 November 2022 at 9:49 AM
To: oracle-livelabs/apex ***@***.***>
Cc: Roopesh Thokala ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/apex] Oracle APEX HOL 01 (PR #37)

file names should be all lowercase

[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/70625227/203468500-59826568-7f3d-4969-82a6-6f50ad8e0521.png__;!!ACWV5N9M2RV99hQ!IMaqxJKlTxa3NPv92RmyOh-obZ9w7tzBQqVTuRTcgQttZNMk48ZC4uZErJaQ-D8zhXm6UMO8wuNOayuzwVNDqnP0gvBDkA$>

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Comment by RoopeshThokala** [comment]
Thank You

From: Madhusudhan Rao ***@***.***>
Date: Wednesday, 23 November 2022 at 3:09 PM
To: oracle-livelabs/apex ***@***.***>
Cc: Roopesh Thokala ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/apex] Oracle APEX HOL 01 (PR #37)

Merged #37<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/apex/pull/37__;!!ACWV5N9M2RV99hQ!MBv1vh2YS4AUFFu9ZZ7gW5U7mAc0uzK9z8Y-BHjvZn2YOD2CVlXDWugPCH250nAFURTf49nVBrcpztJZwHsA-NSLE0CgOQ$> into main.

**Pull request merged**
