### PR TITLE
WMS ID 8641: Movies HOL 22.1 updates

### PR DESCRIPTION
**Pull request by pvhanssen**
Move Movies HOL 21.2 to 21.2 folder and update movies-lab folder to contain lab for APEX 22.1

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. index.html and manifest.json should only be in the `workshops` folder, depending on whether they belong to freetier or Livelabs - can you remove them elsewhere?
2. What is the difference between apex-212/movies-labs and movies-lab? If those two have similar contents, will you remove one of them in the future?
Thanks!

**Comment by madhusudhanrao-ppm** [comment]
Please check movies-labs, it seems to be a duplicate folder 

image

**Comment by arabellayao** [comment]
Followed up on 8/23.

**Comment by pvhanssen** [comment]
Thanks for the comments, removing index.html and manifest.json is in progress. As for the duplicate folders, this is intentional because there are labs for different versions of APEX. So the old movies-lab folder has been moved under the apex-212 folder to be with the other labs that were written for APEX version 21.2. The new movies-lab folder supports APEX 22.1.

**Comment by arabellayao** [comment]
Hi! After you removing index.html and manifest.json, please create a new PR. I am closing this PR since the changes are still in progress, and this will not affect your personal repo. Thanks!

**Pull request closed without merging**
