### PR TITLE
APEX Workflows Lab Update

### PR DESCRIPTION
**Pull request by tomohamm**
# WMS ID : 11525

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [Y] All filenames are lower case (including folders, images, files, etc.)
- [Y] Filenames are descriptive
- [Y] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [N] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [Y] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by hope-fisher — APPROVED** [review]

**Comment by hope-fisher** [comment]
Hi team, 

This branch has one conflict that must be resolved. Can you confirm which of the highlighted paths is correct?
Screenshot 2024-01-12 at 12 19 15 PM

As you move on to the QA and publishing phase, please adjust your estimated times to more accurately reflect the labs.  Consider additional sections (Labs to split up large number of tasks and Tasks to split large numbers of steps). This does not affect this PR review, but is good to keep in mind as you continue the WMS process.

**Comment by tomohamm** [comment]
Hi @hope-fisher, 

The first path - "filename": "../../../common-232/1-sign-up-apex/1-sign-up-apex.md" is the correct one.

**Comment by ramumg** [comment]
Hi @tomohamm, 

Please resolve the conflict in the branch so we can go ahead and merge the changes. 

Thank you!

**Comment by tomohamm** [comment]
Hi @ramumg ,

Conflicts resolved. Please merge the changes.

Thank You.

**Review by ramumg — APPROVED** [review]

**Pull request merged**
