### PR TITLE
WMS ID 8641: Movies HOL 22.1 Updates

### PR DESCRIPTION
**Pull request by pvhanssen**
WMS ID 8641

Created a new Movies HOL for APEX version 22.1. Note that the folders apex-212/movies-lab and apex-211/movie-lab are not duplicates, and instead are versions of this lab for older releases of APEX that still may be needed in the future.

# Checklist
The following is completed:

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. All images should have alternative texts in the Markdown files for accessibility
2. index.html and manifest.json should only be in workshops folder - can you remove them elsewhere?
3. Use this index.html (copy the content) for all your index.html: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/index.html 
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Comment by pvhanssen** [comment]
Hi Arabella,

Are your requested changes referring to the apex-212/movies-hol folder? The apex-212/movies-hol folder is an old version of the lab that we still want to have access to in the event it's ever needed for an old version of APEX (it was moved to the apex-212 folder). The movies-lab is the newest version and does have the following:

- All images in the movies-lab folder have alt text.
- index.html and manifest.json were removed and can only be found in the appropriate folders under the workshops folder.
- The movies-hol/workshops/... index.html folders contain the same content in the index file linked in your comment.

Thanks,
Paige

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Files under movies-lab/2-creating-rest-sources/files should use all lower cases as file names.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please change movies-lab/2-creating-rest-resources/TMDB_Catalog.sql to be all lower case.

**Comment by pvhanssen** [comment]
Apologies, I renamed the file in the references to it in lab 2 but didn't actually change the name of the file itself.
TMDB_Catalog.sql is now tmdb_catalog.sql

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
